project_name: gitimpart
env:
builds:
  - id: gitimpart
    main: ./cmd/gitimpart
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - "386"
changelog:
  use: github-native

release:
  prerelease: auto
